## Numpy_Basics_2
  --> Accessing elements from 1D array  
      --> Indexing  
      --> Negative Indexing  
  --> Accessing elements from 2D array  
      --> Indexing  
  --> Modifying values of the array   
  --> Slicing Arrays  
      --> Positive Slicing   
      --> Negative Slicing   
  --> Accessing Rows and Columns  
  --> Important : Modification Rule  
  --> Copy()  
      --> Important : Copy() Rule   
  --> Reshaping  
  --> newaxis  
  --> Concatination of Array  
      --> concatenate  
      --> hstack  
      --> vstack  
  --> Spliting of Array  
      --> Split  
      --> vsplit  
      --> hsplit  

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
# indexing in numpy is similar to indexing in list

print('First Value-',a[0]) # this gives the output of the first value in the array 
print('Second Value-',a[1]) # this gives the output of the second value in the array 
print('Third Value-',a[2]) # this gives the output of the third value in the array 

First Value- 1
Second Value- 2
Third Value- 3


In [7]:
# You can also use negative indexing to access single elements from a list 

print('Last Value-',a[-1]) # this gives the output of the last value in the array 
print('Second Last Value-',a[-2]) # this gives the output of the second last value in the array 
print('Third Last Value-',a[-3]) # this gives the output of the third last value in the array 

Last Value- 5
Second Last Value- 4
Third Last Value- 3


In [8]:
b = np.array([[1,2,3],[1,4,9],[1,16,81]])
b

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1, 16, 81]])

#### Accessing elements from 2D array

In [9]:
# accessing single elements from multi-dimensional array

# lets take the example of the above array 
# Below is the index numbers of [row,column] for the above array

#  [0,0]  [0,1]  [0,2]
#  [1,0]  [1,1]  [1,2]
#  [2,0]  [2,1]  [2,2]

# the syntax for accessing these elements is - variable_name[row, column]


In [10]:
print("Element on this index 'b[0,0]' ",b[0,0])
print("Element on this index 'b[1,1]' ",b[1,1])
print("Element on this index 'b[2,2]' ",b[2,2])
print("Element on this index 'b[2,0]' ",b[2,0])

Element on this index 'b[0,0]'  1
Element on this index 'b[1,1]'  4
Element on this index 'b[2,2]'  81
Element on this index 'b[2,0]'  1


In [11]:
b

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1, 16, 81]])

#### Modifying values of the array 

In [13]:
# modifying the values in the above array 

print('Non updated array (b)-\n',b)

b[0,2] = 5
b[1,2] = 25
b[2,2] = 125

print("\n")

print("Updated Array (b)-\n",b)

Non updated array (b)-
 [[ 1  2  3]
 [ 1  4  9]
 [ 1 16 81]]


Updated Array (b)-
 [[  1   2   5]
 [  1   4  25]
 [  1  16 125]]


In [14]:
# If we modify the data type of the element to a float the value will be truncated , Ex - 25.912 --> 25

b[1,2] = 25.912
b

array([[  1,   2,   5],
       [  1,   4,  25],
       [  1,  16, 125]])

#### SLICING ARRAYS

In [16]:
ar1 = np.arange(100,110)
ar1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [17]:
# The syntax for slicing is -  variable_name[Start_Index:End_Index:Step_Count]
# If no Values are entered in the syntax, The default values are - Start_index = 0, end_index = length of the dimmension, step_count = 1


In [18]:
# accessing the first 5 elements of the array
ar1[:5]

array([100, 101, 102, 103, 104])

In [19]:
# accessing the elements after the 5th value
ar1[5:]

array([105, 106, 107, 108, 109])

In [20]:
# accessing the middle elements of the array 
ar1[4:7]

array([104, 105, 106])

In [21]:
# accessing every 2nd element of the array 
ar1[::2]

array([100, 102, 104, 106, 108])

In [22]:
# accessing every 3rd element of the array 
ar1[::3]

array([100, 103, 106, 109])

In [23]:
# accessing every 3rd element, starting from index at 1 
ar1[1::3]

array([101, 104, 107])

In [25]:
# accessing every 2nd element, starting from index 2 and ending at index 7 
ar1[2:7:2]

array([102, 104, 106])

In [26]:
# In negative slicing , the start index and the end index are swapped 

ar1 

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [27]:
ar1[::-1] # the entire array is reversed 

array([109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [29]:
# reversed elements ending upto 5th value
ar1[5::-1]

array([105, 104, 103, 102, 101, 100])

In [30]:
# reversed elements starting after the 2nd value
ar1[:2:-1]

array([109, 108, 107, 106, 105, 104, 103])

In [31]:
# reversed elements starting after the 2nd value and ending upto the 5th value
ar1[5:2:-1]

array([105, 104, 103])

In [32]:
# reversed elements starting after 1st value and ending upto the 6th value with a step count of 2
ar1[6:1:-2]

array([106, 104, 102])

In [35]:
ar2 = np.array([[2,3,5],[4,9,25],[16,81,125]])
ar2


array([[  2,   3,   5],
       [  4,   9,  25],
       [ 16,  81, 125]])

In [37]:
# accessing multi dimensional array 
               #                          Row                                    Column
               # variable_name[start_index :end_index:step_count,  start_index:end_index:step_count]

In [39]:
ar2[:2,:2] # accessing 2 rows and 2 columns 

array([[2, 3],
       [4, 9]])

In [41]:
ar3 = np.array([[1,2,3,4,5],[11,22,33,44,55],[21,32,43,54,65],[70,80,90,100,110],[200,300,400,500,600]])
ar3

array([[  1,   2,   3,   4,   5],
       [ 11,  22,  33,  44,  55],
       [ 21,  32,  43,  54,  65],
       [ 70,  80,  90, 100, 110],
       [200, 300, 400, 500, 600]])

In [42]:
# accessing 3 rows and 4 columns
ar3[:3,:4] 

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [21, 32, 43, 54]])

In [43]:
# accessing all rows and alternate columns
ar3[:,::2]

array([[  1,   3,   5],
       [ 11,  33,  55],
       [ 21,  43,  65],
       [ 70,  90, 110],
       [200, 400, 600]])

In [44]:
# accessing alternate rows and all columns
ar3[::2,:]

array([[  1,   2,   3,   4,   5],
       [ 21,  32,  43,  54,  65],
       [200, 300, 400, 500, 600]])

In [45]:
# accessing reversed rows and columns
ar3[::-1,::-1]

array([[600, 500, 400, 300, 200],
       [110, 100,  90,  80,  70],
       [ 65,  54,  43,  32,  21],
       [ 55,  44,  33,  22,  11],
       [  5,   4,   3,   2,   1]])

In [ ]:
# Negative Indexing for the above array 
#     4      3      2      1       0
#  [ 600    500    400    300    200]   4
#  [ 110    100    90     80     70]    3
#  [ 65     54     43     32     21]    2
#  [ 55     44     33     22     11]    1
#  [ 5      4      3      2       1]    0

In [65]:
# accessing the values 
# [100, 90]
# [54, 43]
# using reversed slicing 

ar3[3:1:-1, 3:1:-1]

array([[100,  90],
       [ 54,  43]])

In [66]:
# accessing the values 
# [500, 400, 300]
# [100, 90, 80]
# using reversed slicing

ar3[:2:-1,3:0:-1]

array([[500, 400, 300],
       [100,  90,  80]])

#### Accessing Rows and Columns

In [ ]:
# Accessing Rows and Columns

In [67]:
# Syntax -- variable_name[row,column]
ar3[:,0] # gives the first column of the array -- ':' means all rows and '0' states the first column

array([  1,  11,  21,  70, 200])

In [69]:
ar3[0,:] # gives the first row of the array -- '0' means all the rows and ':' means all the columns

array([1, 2, 3, 4, 5])

In [70]:
ar3[0] # if you omit the [row,column] syntax then by default all rows and columns are printed of the specified index

array([1, 2, 3, 4, 5])

In [71]:
ar3[2] # if you omit the [row,column] syntax then by default all rows and columns are printed of the specified index

array([21, 32, 43, 54, 65])

In [72]:
ar2

array([[  2,   3,   5],
       [  4,   9,  25],
       [ 16,  81, 125]])

#### IMP Modification Rule

In [ ]:
# In the below example we can see that after making a modification in the substring the original string is also being changed
# Reason for this :
# Any modifications made to the subarray will also reflect in the main array, because they both point to the same memory location

In [74]:
ar2_sub = ar2[:2,:2]
ar2_sub

array([[2, 3],
       [4, 9]])

In [76]:
ar2_sub[0,0]= 999
ar2_sub

array([[999,   3],
       [  4,   9]])

In [77]:
ar2

array([[999,   3,   5],
       [  4,   9,  25],
       [ 16,  81, 125]])

#### Copy()

In [80]:
# Creating Copies of arrays
# This method prevents the above behaviour 

ar2[0,0] = 2
print(ar2,'\n')
print(ar2_sub)

[[  2   3   5]
 [  4   9  25]
 [ 16  81 125]] 

[[2 3]
 [4 9]]


In [82]:
ar2_sub = ar2[:2,:2].copy() # Here we are extracting a subarray from ar2 and creating a copy of it 
ar2_sub

array([[2, 3],
       [4, 9]])

In [83]:
# Hence it is clear 
# Any modifications made to the subarray will not reflect in the main array,
# because 'ar2_sub' is a copy and resides in a different memory location

ar2_sub[0,0] = 99
print(ar2,'\n')
print(ar2_sub)

[[  2   3   5]
 [  4   9  25]
 [ 16  81 125]] 

[[99  3]
 [ 4  9]]


#### Reshaping

In [84]:
a = np.arange(1,10).reshape((3,3)) # reshape() is used for reshaping the array 
a                                  # Note : the size of the initial array must match the size of the reshaped array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
a = np.arange(1,6).reshape((2,2)) # This error has occured due the following reason 
a                                 # The elements in the array are - 1, 2, 3, 4, 5
                                  # The shape provided is (2,2) - which means it has 2 rows and 2 columns
                                  # So the maping 5 elements in 3x3 matrix is not possible 
                                  # 1  2  3
                                  # 4  5  -      [this causes the error]

ValueError: cannot reshape array of size 5 into shape (2,2)

In [92]:
# solving the above error

a = np.arange(1,5).reshape((2,2)) # The elements in the array are - 1, 2, 3, 4
a                                 # 1  2  
                                  # 3  4

array([[1, 2],
       [3, 4]])

#### newaxis

In [95]:
# The syntax for creating a row vector - [np.newaxis,:]
# The syntax for creating a column vector - [:,np.newaxis]

In [96]:
ar = np.array([1,2,3,4])
ar

array([1, 2, 3, 4])

In [100]:
# creating a row vector using newaxis

row_vector = ar[np.newaxis,:]

print("Array - ",ar,' Shape-',ar.shape) # this give the shape of the ar array which is (4,) 4 is the number of elements 
                                         # In 1D, the array does not have rows and columns, its just single line of elements
    
print("Row vector ",row_vector,' Shape',row_vector.shape)# this gives the shape of the row_vector which is (1,4)
                                                         # The question arises how are we getting the values (1,4)
                                                         # Here by using the newaxis, we are adding a new axis at the row level in other words converting it to a 2D array which has 1 row and 4 columns
                                                        
                                                         #     column1  column2  column3   column4
                                                         # row    1         2        3        4
                    
                                                        # you can even see the output of the arrays and identify which is 1D and which is a 2D

Array -  [1 2 3 4]  Shape- (4,)
Row vector  [[1 2 3 4]]  Shape (1, 4)


In [101]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [104]:
# creating a column vector using newaxis 

column_vector = arr[:,np.newaxis]


print("Array-",arr,'shape-',arr.shape) # this give the shape of the arr array which is (4,) 4 is the number of elements 
                                       # In 1D, the array does not have rows and columns, its just single line of elements
    
print("Column vector-",column_vector,'shape-',column_vector.shape) # this gives the shape of the column_vector which is (4,1)
                                                         # The question arises how are we getting the values (4,1)
                                                         # Here by using the newaxis, we are adding a new axis at the column level in other words converting it to a 2D array which has 4 rows and 1 column
                                                        
                                                         #     column  
                                                         # row1    1         
                                                         # row2    2         
                                                         # row3    3         
                                                         # row4    4         
                                                        # you can even see the output of the arrays and identify which is 1D and which is a 2D

Array- [1 2 3 4] shape- (4,)
Column vector- [[1]
 [2]
 [3]
 [4]] shape- (4, 1)


#### Concatination of Array

In [109]:
import numpy as np
ar= np.array([1,2,3,4])
br = np.array([4,5,6,7,8])
print(ar,'\n',br)


[1 2 3 4] 
 [4 5 6 7 8]


In [111]:
# concating two 1D array
np.concatenate([ar,br])

array([1, 2, 3, 4, 4, 5, 6, 7, 8])

In [112]:
# concating three 1D array 
cr =np.arange(1,10)

d = np.concatenate([ar,br,cr])
print("Concat of 3- 1D arrays-",d)

Concat of 3- 1D arrays- [1 2 3 4 4 5 6 7 8 1 2 3 4 5 6 7 8 9]


In [115]:
arr = np.array([[1,2,3],[4,5,6]])
brr = np.array([[7,8,9],[0,1,2]])
print(arr,'\n\n',brr)

[[1 2 3]
 [4 5 6]] 

 [[7 8 9]
 [0 1 2]]


In [116]:
# concating two 2D arrays

np.concatenate([arr,brr])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [118]:
# concating three 2D arrays

crr = np.array([[11,22,33],[100,200,300]])
d = np.concatenate([arr,brr,crr])

print("Concated array-\n",d)

Concated array-
 [[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [  0   1   2]
 [ 11  22  33]
 [100 200 300]]


In [119]:
# If you are using two arrays of different dimensions you can use the np.vstack[vertical stack] and np.hstack [horizontal stack]

In [123]:
x = np.array([1,2,3])
y = np.array([[3,4,5],[9,8,7]])

np.vstack([y,x])   # np.vstack stacks arrays in row-wise stacking
                   # To stack arrays vertically-
                   # All arrays must have the same number of columns   

array([[3, 4, 5],
       [9, 8, 7],
       [1, 2, 3]])

In [128]:

a = np.array([1,2,3])      # Shape (3,)

a = a[np.newaxis,:]        # Shape(1,3)

b = np.array([[22,33,44]]) # Shape(1,3)

np.hstack([a,b])             # np.hstack - stacks the arrays in column-wise stacking
                             # The arrays must have the same number of rows (same height) to align properly
    
                             # The reason why I used row_vectoring is to make the rows of both the arrays equal for successful execution of the code 
                             # If the rows are not equal then a ValueError is raised 

array([[ 1,  2,  3, 22, 33, 44]])

In [136]:
a1 = np.array([1,2,3])                           # Shape(3,)
a1 = a1[:,np.newaxis]                            # Shape(3,1)
b = np.array([[1,23,44,54],[0,9,8,7],[4,3,2,1]]) # Shape(3,4)

np.hstack([a1,b])

array([[ 1,  1, 23, 44, 54],
       [ 2,  0,  9,  8,  7],
       [ 3,  4,  3,  2,  1]])

#### Splitting of Arrays 

In [140]:
arr1 = np.array([1,2,5,6,8,9])
np.split(arr1,2)  # Here the split function divides the array into two equal parts and prints the output
                  # length of the array arr = 6 ,spliting it into 2 equal halves gives us 3 elements in each row 
   

 # Important Note - 
    # if an array has 3 elements and we want to split it into 2 equal halves then this code will raise an error
    # The total number of elements (3) must be divisible by the number of splits (2)
    # Example: 
    # arr = np.array([1,2,3])
    # np.split(arr,2)

[array([1, 2, 5]), array([6, 8, 9])]

In [144]:
arr1

array([1, 2, 5, 6, 8, 9])

In [146]:
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:

print("Array is split into two equal halves-",np.array_split(ar,2))
print("Array is split into 3 havles- ",np.array_split(ar,3))

# Final Note -

# np.split() : strictly requires the array size to be evenly divisible by the number of splits specified. 
# If it isn't, it raises a ValueError

# np.array_split() is more flexible. 
# It allows splitting the array into unequal parts when the array size isn't evenly divisible by the number of splits

Array is split into two equal halves- [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
Array is split into 3 havles-  [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [167]:
# hsplit -- Horizontal split 
# this works on arrays with at least 2D
# Splits the array along its columns

ar = np.array([[1,2,3,4,5,6],[6,7,8,9,0,1]])      # 1  2  3  4  5  6
                                                  # 6  7  8  9  0  1
    
                                             # horizontal split is done on columns. There are 6 columns and dividing them by (3) splits provides total 3 groups of arrays
                                             # ([[1,2],[6,7]])     ([[3,4],[8,9]])    ([[5,6],[0,1]])
np.hsplit(ar,3)

[array([[1, 2],
        [6, 7]]),
 array([[3, 4],
        [8, 9]]),
 array([[5, 6],
        [0, 1]])]

In [184]:
# np.vsplit -- Vertical Split
# Splits the array along its row
# Works only on arrays with at least 2 dimensions

arr1 = np.full((4,4),4)
arr1

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [186]:
np.vsplit(arr1,2)                                 # 4  4  4  4  4  4
                                                  # 4  4  4  4  4  4
                                                  # 4  4  4  4  4  4
                                                  # 4  4  4  4  4  4
    
                                             # vertical split is done on rows. There are 4 columns and dividing them by (2) splits provides total 2 groups of arrays
                                             # ([[4,4,4,4],[4,4,4,4]])    ([[4,4,4,4],[4,4,4,4]])

[array([[4, 4, 4, 4],
        [4, 4, 4, 4]]),
 array([[4, 4, 4, 4],
        [4, 4, 4, 4]])]